export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_LOADED_SAGA = "DATA_LOADED_SAGA";
export const API_ERRORED_SAGA = "API_ERRORED_SAGA";
export const DATA_REQUESTED = "DATA_REQUESTED";
